services:
  - type: web
    name: simple-shift-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:${PORT:-5000} app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.4
